spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=1h
  scheduler:
    recurring-cron: 0 0 1 * * *
  datasource:
    url: jdbc:postgresql://postgres:5432/expense_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog-master.xml
    contexts: dev
    clear-checksums: false
    drop-first: false
  elasticsearch:
    uris: http://elasticsearch:9200

server:
  port: 8080
