spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=1h
  scheduler:
    recurring-cron: 0 0 3 * * *
    zone: Europe/Moscow
  application:
    name: expense-tracker
  messages:
    basename: ValidationMessages
    encoding: UTF-8
  web:
    locale: ru
    locale-resolver: fixed

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    com.example.expensetracker: DEBUG

app:
  jwt:
    secret: "Nohackerwilleverguessthiskeynotevenyou12345"
    access-expiration: 900000
    refresh-expiration: 604800000
  admin:
    email: admin@example.com
    password: admin